flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, EqualTo, ValidationError

class PostForm(FlaskForm):
    title = StringField('Title',validators=[DataRequired()])
    content = TextAreaField('Content',validators=[DataRequired()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpeg','jpg', 'png'])])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    content = TextAreaField('Content')
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Post')

flaskblog/main/routes.py
import pusher
from flask import render_template, jsonify,request, Blueprint,redirect
from flaskblog import db
from flask_login import current_user, login_required
from flaskblog.models import Post,Message,User
from datetime import datetime
from pytz import timezone
import pytz
import json
import pprint
import sys
import spotipy
import spotipy.util as util

pusher_client = pusher.Pusher(
  app_id='541241',
  key='d199b9ff7984c46c4f83',
  secret='e0d579e55a6e83dd7397',
  cluster='us2',
  ssl=True
)

main = Blueprint('main', __name__)



@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route("/get-count",methods=['POST'])
def get_count():
    try:
        countdict = pusher_client.channel_info(u'chatchannel', [u"subscription_count"])
        count = countdict['subscription_count']
        pusher_client.trigger('chatchannel', 'update-count', {'count':count})
        return jsonify({'result' : 'success'})
    except:
        print('ERROR')
        return jsonify({'result' : 'failure'})

@main.route("/message",methods=['POST'])
def message():
    try:
        username = request.form.get('username')
        message = request.form.get('message')
        user = User.query.filter_by(username=username).first()
        time = timezone('US/Pacific')
        new_message = Message(username=username, message=message,image_file=user.image_file,date_posted=datetime.now(time))
        image = user.image_file
        db.session.add(new_message)
        db.session.commit()
        time = new_message.date_posted.strftime('%B %d %Y - %H:%M:%S')
        pusher_client.trigger('chatchannel', 'new-message', {'username' : username, 'message': message,'time':time,'image':image})
        return jsonify({'result' : 'success'})

    except:
        print('Error')
        return jsonify({'result' : 'failure'})

@main.route('/test')
@login_required
def test():
    messages = Message.query.all()
    return render_template('test.html',messages=messages)

@main.route("/about")
def about():
    return render_template('about.html', title='About')

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, jsonify ,abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db,bcrypt
from flaskblog.models import Post,Comment,Like,Dislike,LikeComment,DislikeComment
from flaskblog.posts.forms import PostForm, CommentForm
from flaskblog.users.utils import save_picture

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            post.post_image = picture_file
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    comments = Comment.query.filter_by(post_id=post_id).order_by(Comment.date_posted.desc()).paginate(page=page, per_page=5)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(content=form.content.data, author=current_user,post_id=post_id)
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            comment.comment_image = picture_file
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been created!', 'success')
        return redirect(url_for('posts.post',post_id=post.id))
    return render_template('post.html', title=post.title, post=post, form=form, comments=comments,legend='Leave a comment')


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            post.post_image = picture_file
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')



def delete_all_comments(post_id):
    comments = Comment.query.filter_by(post_id=post_id)
    for comment in comments:
        commentlikes = LikeComment.query.filter_by(comment_id=comment.id)
        for commentlike in commentlikes:
            db.session.delete(commentlike)

        commentdislikes = DislikeComment.query.filter_by(comment_id=comment.id)
        for commentdislike in commentdislikes:
            db.session.delete(commentdislike)
        db.session.delete(comment)

def delete_all_likes_and_dislikes(post_id):
    likes = Like.query.filter_by(post_id=post_id)
    for like in likes:
        db.session.delete(like)

    dislikes = Dislike.query.filter_by(post_id=post_id)
    for dislike in dislikes:
        db.session.delete(dislike)

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    delete_all_comments(post_id)
    delete_all_likes_and_dislikes(post_id)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

@posts.route("/post/<int:post_id>/<int:comment_id>/delete", methods=['POST'])
@login_required
def delete_comment(comment_id,post_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.author != current_user:
        abort(403)
    db.session.delete(comment)
    delete_all_likes_and_dislikes(comment_id)
    db.session.commit()
    flash('Your comment has been deleted!', 'success')
    return redirect(url_for('posts.post',post_id=post_id))


@posts.route('/like/', methods=['GET','POST'])
@login_required
def like():
    num = float(request.form.get('number', 0))
    dislikecount = float(request.form.get('dislikecount', 0))
    post_id = request.form.get('post_id',0)
    likesearch = Like.query.filter_by(user_id=current_user.id,post_id=post_id).first()
    dislikesearch = Dislike.query.filter_by(user_id=current_user.id,post_id=post_id).first()

    if likesearch is None:
        post = Post.query.get_or_404(post_id)
        post.likes_count+=1
        like = Like(user_id=current_user.id,post_id=post_id)

        if dislikesearch is None:
            pass
        else:
            post.dislikes-=1
            dislikecount-=1
            db.session.delete(dislikesearch)

        db.session.add(like)
        db.session.commit()
        result = num + 1
        data = {'result': result,'dislikecount':dislikecount,'color':"Green"}
        data = jsonify(data)
        return data
    else:
        post = Post.query.get_or_404(post_id)
        post.likes_count-=1
        db.session.delete(likesearch)
        db.session.commit()
        result = num - 1
        data = {'result': result,'color':"Red"}
        data = jsonify(data)
        return data

@posts.route('/dislike/', methods=['GET','POST'])
@login_required
def dislike():
    num = float(request.form.get('number', 0))
    likecount = float(request.form.get('likecount', 0))
    post_id = request.form.get('post_id',0)
    dislikesearch = Dislike.query.filter_by(user_id=current_user.id,post_id=post_id).first()
    likesearch = Like.query.filter_by(user_id=current_user.id,post_id=post_id).first()

    if dislikesearch is None:
        post = Post.query.get_or_404(post_id)
        post.dislikes+=1
        if likesearch is None:
            pass
        else:
            post.likes_count-=1
            likecount-=1
            db.session.delete(likesearch)

        dislike = Dislike(user_id=current_user.id,post_id=post_id)
        db.session.add(dislike)
        db.session.commit()
        result = num + 1
        data = {'result': result,'likecount':likecount,'color':"Green"}
        data = jsonify(data)
        return data
    else:
        post = Post.query.get_or_404(post_id)
        post.dislikes-=1
        db.session.delete(dislikesearch)
        db.session.commit()
        result = num - 1
        data = {'result': result,'color':"Red"}
        data = jsonify(data)
        return data

@posts.route('/comment/like', methods=['GET','POST'])
@login_required
def like_comment():
    num = float(request.form.get('number', 0))
    dislikecount = float(request.form.get('dislikecount', 0))
    comment_id = request.form.get('comment_id',0)
    likesearch = LikeComment.query.filter_by(user_id=current_user.id,comment_id=comment_id).first()
    dislikesearch = DislikeComment.query.filter_by(user_id=current_user.id,comment_id=comment_id).first()

    if likesearch is None:
        comment = Comment.query.get_or_404(comment_id)
        comment.likes_count+=1
        like = LikeComment(user_id=current_user.id,comment_id=comment_id)

        if dislikesearch is None:
            pass
        else:
            comment.dislikes-=1
            dislikecount-=1
            db.session.delete(dislikesearch)

        db.session.add(like)
        db.session.commit()
        result = num + 1
        data = {'result': result,'dislikecount':dislikecount,'color':"Green"}
        data = jsonify(data)
        return data
    else:
        comment = Comment.query.get_or_404(comment_id)
        comment.likes_count-=1
        db.session.delete(likesearch)
        db.session.commit()
        result = num - 1
        data = {'result': result,'color':"Red"}
        data = jsonify(data)
        return data

@posts.route('/comment/dislike', methods=['GET','POST'])
@login_required
def dislike_comment():
    num = float(request.form.get('number', 0))
    likecount = float(request.form.get('likecount', 0))
    comment_id = request.form.get('comment_id',0)
    dislikesearch = DislikeComment.query.filter_by(user_id=current_user.id,comment_id=comment_id).first()
    likesearch = LikeComment.query.filter_by(user_id=current_user.id,comment_id=comment_id).first()

    if dislikesearch is None:
        comment = Comment.query.get_or_404(comment_id)
        comment.dislikes+=1
        if likesearch is None:
            pass
        else:
            comment.likes_count-=1
            likecount-=1
            db.session.delete(likesearch)

        dislike = DislikeComment(user_id=current_user.id,comment_id=comment_id)
        db.session.add(dislike)
        db.session.commit()
        result = num + 1
        data = {'result': result,'likecount':likecount,'color':"Green"}
        data = jsonify(data)
        return data
    else:
        comment = Comment.query.get_or_404(comment_id)
        comment.dislikes-=1
        db.session.delete(dislikesearch)
        db.session.commit()
        result = num - 1
        data = {'result': result,'color':"Red"}
        data = jsonify(data)
        return data

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)



@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
  <h1>About Page</h1>
  <p>
    Test website done mainly with Flask and Python for education purposes.
  </p>
{% endblock %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    {% for post in posts.items %}
    <script type="text/javascript">
       $(document).ready(function() {
         $("#{{post.id}}_like").click(function() {
           var number = $('#{{post.id}}_like_result').text();
           var dislikecount = $('#{{post.id}}_dislike_result').text();
           var post_id = "{{post.id}}";
           $.ajax({
              url: "{{ url_for('posts.like') }}",
              data: {'number': number,'dislikecount':dislikecount,'post_id':post_id},
              method: 'POST',
              success: function(data) {
                $('#{{post.id}}_like_result').html(data['result'])
                $('#{{post.id}}_dislike_result').html(data['dislikecount'])
                if (data['color'] == "Green")
                {
                $('#{{post.id}}_like').removeClass("btn-outline-primary").addClass("btn-primary");
                $('#{{post.id}}_dislike').removeClass("btn-danger").addClass("btn-outline-danger");
              }else{
                $('#{{post.id}}_like').removeClass("btn-primary").addClass("btn-outline-primary");
              }}
            });
         });
       });
        </script>
        <script type="text/javascript">
           $(document).ready(function() {
             $("#{{post.id}}_dislike").click(function() {
               var number = $('#{{post.id}}_dislike_result').text();
               var likecount = $('#{{post.id}}_like_result').text();
               var post_id = "{{ post.id }}";
               $.ajax({
                  url: "{{ url_for('posts.dislike') }}",
                  data: {'number': number,'likecount':likecount,'post_id':post_id},
                  method: 'POST',
                  success: function(data) {
                    $('#{{post.id}}_dislike_result').html(data['result'])
                    $('#{{post.id}}_like_result').html(data['likecount'])
                    if (data['color'] == "Green")
                    {
                    $('#{{post.id}}_dislike').removeClass("btn-outline-danger").addClass("btn-danger");
                    $('#{{post.id}}_like').removeClass("btn-primary").addClass("btn-outline-primary");

                  }else{
                    $('#{{post.id}}_dislike').removeClass("btn-danger").addClass("btn-outline-danger");
                  }}
                });
             });
           });
            </script>
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%B %d %Y - %H:%M:%S') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>

            {% if post.post_image != 'None' %}
            <a data-toggle="modal" data-target="#{{post.id}}"><img src="{{ url_for('static', filename='profile_pics/' + post.post_image) }}" style="float:center;width:100%;height:100%;object-fit:cover;"/></a>
                      <div id="{{post.id}}" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                          <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <img src="{{ url_for('static', filename='profile_pics/' + post.post_image) }}" style="float:center;width:100%;height:100%;object-fit:cover;" class="img-responsive">
                                </div>
                            </div>
                          </div>
                      </div>
            {% endif %}
            {% if post.content %}
            {% if post.find_links(post.content) %}
              <iframe width="560" height="315" src="https://www.youtube.com/embed/{{post.embed_link(post.content)}}" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
            {% endif %}
            <p class="article-content">{{ post.content }}</p>
            {% endif %}
            {% if current_user.is_authenticated %}

            <div class="like-and-dislike">
              <hr>

              {% if post.check_liked(current_user.id,post.id) %}
              <button class="btn btn-primary" id='{{post.id}}_like'><ion-icon name="thumbs-up" size="medium"></ion-icon>  Likes: <span id="{{post.id}}_like_result">{{post.likes_count}}</span></button>
              {% else %}
              <button class="btn btn-outline-primary" id='{{post.id}}_like'><ion-icon name="thumbs-up" size="medium"></ion-icon>  Likes: <span id="{{post.id}}_like_result">{{post.likes_count}}</span></button>
              {% endif %}
              {% if post.check_disliked(current_user.id,post.id) %}
              <button style="float:right;" class="btn btn-danger" id='{{post.id}}_dislike'><ion-icon name="thumbs-down" size="medium"></ion-icon>  Dislikes:     <span id="{{post.id}}_dislike_result">{{post.dislikes}}</span></button>
              {% else %}
              <button style="float:right;" class="btn btn-outline-danger" id='{{post.id}}_dislike'><ion-icon name="thumbs-down" size="medium"></ion-icon>  Dislikes: <span id="{{post.id}}_dislike_result">{{post.dislikes}}</span></button>
              {% endif %}

            {% else %}

              <a href="{{ url_for('users.login') }}"><button class="btn btn-outline-primary"><ion-icon name="thumbs-up" size="medium"></ion-icon>  Likes:     <span>{{post.likes_count}}</span></button></a>
              <a href="{{ url_for('users.login') }}"><button style="float:right;" class="btn btn-outline-danger"><ion-icon name="thumbs-down" size="medium"></ion-icon>  Dislikes:     <span>{{post.dislikes}}</span></button></a>

            {% endif %}
            <span>Comments: {{post.count_comments(post.id)}}</span>

          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}



{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/v4-shims.css">    {% if title %}
        <title>Shitty Test Website - {{ title }}</title>
    {% else %}
        <title>Shitty Test Website</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4 " href="/"><span class="icon-nav">Shitty Test Website</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}"><ion-icon class="icon-nav" name="md-home" size="large"></ion-icon><span class="icon-nav">   Home</span></a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}"><ion-icon class="icon-nav" name="md-information-circle" size="large"></ion-icon><span class="icon-nav">   About</span></a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}"><ion-icon class="icon-nav" name="md-add-circle" size="large"></ion-icon><span class="icon-nav">   New Post</span></a>
                <a class="nav-item nav-link" href="#"><ion-icon class="icon-nav" name="chatboxes" size="large"></ion-icon>  <span class="icon-nav"> Chat </span></a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}"><ion-icon class="icon-nav" name="contact" size="large"></ion-icon>  <span class="icon-nav">   Account</span></a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}"><ion-icon class="icon-nav" name="log-out" size="large"></ion-icon><span class="icon-nav"> Logout</span></a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}"><ion-icon class="icon-nav" name="log-in" size="large"></ion-icon><span class="icon-nav">   Log in</span></a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}"><ion-icon class="icon-nav" name="person-add" size="large"></ion-icon><span class="icon-nav">   Register</span></a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>


      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/ionicons@4.1.2/dist/ionicons.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script type=text/javascript src="{{url_for('static', filename='jquery.js') }}"></script>
    <script type=text/javascript>
      $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}